name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read  # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use latest deno version
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run deno build script
        run: deno run --allow-read --allow-write build.ts

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
      - name: Build using wasm-pack
        run: cd ./corul-wasm && wasm-pack build --release --target web
        
      - name: Go back to base dir
        run: cd ..

      - name: Bundle deno server code
        run: deno bundle ./server.ts -- ./server.bundle.js

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "corul-web-app"
          entrypoint: "./server.bundle.js"
